services:
  - type: web
    name: telegram-roulette-bot
    env: python
    rootDir: .          # ajuste se seu código estiver em subpasta (ex.: "bot/")
    buildCommand: |
      python --version
      pip install -r requirements.txt
      python -m playwright install --with-deps chromium
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
      - key: USE_WEBHOOK
        value: "true"
      - key: WEBHOOK_URL
        value: "https://SEU-SERVICO.onrender.com"
    healthCheckPath: /health
    autoDeploy: true
